/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BucketId = bigint;
export type Column = { 'Blocked' : null } |
  { 'Done' : null } |
  { 'Todo' : null } |
  { 'Doing' : null };
export interface CreateBucketArgs {
  'name' : string,
  'color' : string,
  'workspaceId' : WorkspaceId,
}
export interface CreateMilestoneArgs {
  'endDate' : Timestamp,
  'name' : string,
  'template' : SprintTemplate,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
}
export interface CreateSprintArgs {
  'endDate' : Timestamp,
  'goal' : string,
  'name' : string,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
}
export interface CreateTaskArgs {
  'title' : string,
  'assigneeId' : [] | [UserId],
  'order' : bigint,
  'sprintId' : [] | [SprintId],
  'dueDate' : [] | [Timestamp],
  'bucketId' : [] | [BucketId],
  'description' : string,
  'workspaceId' : WorkspaceId,
  'priority' : Priority,
  'department' : [] | [Department],
  'columnId' : Column,
}
export interface CreateWorkspaceArgs {
  'tagline' : string,
  'name' : string,
  'logoUrl' : string,
}
export type Department = { 'Engineering' : null } |
  { 'Operations' : null } |
  { 'Design' : null } |
  { 'Management' : null } |
  { 'Marketing' : null };
export type MemberRole = { 'Lead' : null } |
  { 'Member' : null } |
  { 'Admin' : null } |
  { 'CoCreator' : null };
export type MilestoneId = bigint;
export interface MilestonePublic {
  'id' : MilestoneId,
  'endDate' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
}
export interface MoveTaskArgs {
  'blockerReason' : string,
  'newOrder' : bigint,
  'newColumn' : Column,
  'taskId' : TaskId,
}
export type Priority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type SprintId = bigint;
export interface SprintPublic {
  'id' : SprintId,
  'status' : SprintStatus,
  'endDate' : Timestamp,
  'goal' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
}
export type SprintStatus = { 'Active' : null } |
  { 'Planned' : null } |
  { 'Completed' : null };
export type SprintTemplate = { 'TwoSprints' : null } |
  { 'FourSprints' : null };
export interface TaskBucketPublic {
  'id' : BucketId,
  'name' : string,
  'createdAt' : Timestamp,
  'color' : string,
  'workspaceId' : WorkspaceId,
}
export type TaskId = bigint;
export interface TaskPublic {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'blockerReason' : string,
  'assigneeId' : [] | [UserId],
  'order' : bigint,
  'sprintId' : [] | [SprintId],
  'createdAt' : Timestamp,
  'dueDate' : [] | [Timestamp],
  'bucketId' : [] | [BucketId],
  'description' : string,
  'workspaceId' : WorkspaceId,
  'priority' : Priority,
  'department' : [] | [Department],
  'columnId' : Column,
}
export type TaskStatus = { 'Blocked' : null } |
  { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type Timestamp = bigint;
export interface UpdateBucketArgs { 'name' : string, 'color' : string }
export interface UpdateMilestoneArgs {
  'endDate' : Timestamp,
  'name' : string,
  'startDate' : Timestamp,
}
export interface UpdateProfileArgs {
  'bio' : string,
  'title' : string,
  'name' : string,
  'onboardingComplete' : boolean,
  'avatarUrl' : string,
  'department' : string,
}
export interface UpdateSprintArgs {
  'status' : SprintStatus,
  'endDate' : Timestamp,
  'goal' : string,
  'name' : string,
  'startDate' : Timestamp,
}
export interface UpdateTaskArgs {
  'status' : TaskStatus,
  'title' : string,
  'blockerReason' : string,
  'assigneeId' : [] | [UserId],
  'order' : bigint,
  'sprintId' : [] | [SprintId],
  'dueDate' : [] | [Timestamp],
  'bucketId' : [] | [BucketId],
  'description' : string,
  'priority' : Priority,
  'department' : [] | [Department],
  'columnId' : Column,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'bio' : string,
  'title' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'onboardingComplete' : boolean,
  'avatarUrl' : string,
  'department' : string,
}
export interface Workspace {
  'id' : WorkspaceId,
  'ownerId' : UserId,
  'tagline' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'logoUrl' : string,
}
export type WorkspaceId = bigint;
export interface WorkspaceMember {
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : MemberRole,
}
export interface _SERVICE {
  'completeOnboarding' : ActorMethod<[], undefined>,
  'createBucket' : ActorMethod<[CreateBucketArgs], TaskBucketPublic>,
  'createMilestone' : ActorMethod<[CreateMilestoneArgs], MilestonePublic>,
  'createOrUpdateProfile' : ActorMethod<[UpdateProfileArgs], UserProfilePublic>,
  'createSprint' : ActorMethod<[CreateSprintArgs], SprintPublic>,
  'createTask' : ActorMethod<[CreateTaskArgs], TaskPublic>,
  'createWorkspace' : ActorMethod<[CreateWorkspaceArgs], Workspace>,
  'deleteBucket' : ActorMethod<[BucketId], undefined>,
  'deleteMilestone' : ActorMethod<[MilestoneId], undefined>,
  'deleteSprint' : ActorMethod<[SprintId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getActiveSprint' : ActorMethod<[WorkspaceId], [] | [SprintPublic]>,
  'getBucket' : ActorMethod<[BucketId], [] | [TaskBucketPublic]>,
  'getMilestone' : ActorMethod<[MilestoneId], [] | [MilestonePublic]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyWorkspaces' : ActorMethod<[], Array<Workspace>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getSprint' : ActorMethod<[SprintId], [] | [SprintPublic]>,
  'getSprintInviteLink' : ActorMethod<[SprintId], string>,
  'getSprintInviteLinkQuery' : ActorMethod<[SprintId], [] | [string]>,
  'getTask' : ActorMethod<[TaskId], [] | [TaskPublic]>,
  'getWorkspace' : ActorMethod<[WorkspaceId], [] | [Workspace]>,
  'getWorkspaceOwner' : ActorMethod<[WorkspaceId], [] | [UserId]>,
  'initSampleData' : ActorMethod<[], undefined>,
  'inviteMember' : ActorMethod<[WorkspaceId, UserId, MemberRole], undefined>,
  'isWorkspaceCreator' : ActorMethod<[WorkspaceId], boolean>,
  'listBuckets' : ActorMethod<[WorkspaceId], Array<TaskBucketPublic>>,
  'listMembers' : ActorMethod<[WorkspaceId], Array<WorkspaceMember>>,
  'listMilestones' : ActorMethod<[WorkspaceId], Array<MilestonePublic>>,
  'listSprints' : ActorMethod<[WorkspaceId], Array<SprintPublic>>,
  'listTasksByAssignee' : ActorMethod<[WorkspaceId, UserId], Array<TaskPublic>>,
  'listTasksByColumn' : ActorMethod<[WorkspaceId, Column], Array<TaskPublic>>,
  'listTasksBySprint' : ActorMethod<[WorkspaceId, SprintId], Array<TaskPublic>>,
  'moveTask' : ActorMethod<[MoveTaskArgs], TaskPublic>,
  'registerProfile' : ActorMethod<[], UserProfilePublic>,
  'removeMember' : ActorMethod<[WorkspaceId, UserId], undefined>,
  'setSprintStatus' : ActorMethod<[SprintId, SprintStatus], SprintPublic>,
  'updateBucket' : ActorMethod<[BucketId, UpdateBucketArgs], TaskBucketPublic>,
  'updateMemberRole' : ActorMethod<
    [WorkspaceId, UserId, MemberRole],
    undefined
  >,
  'updateMilestone' : ActorMethod<
    [MilestoneId, UpdateMilestoneArgs],
    MilestonePublic
  >,
  'updateSprint' : ActorMethod<[SprintId, UpdateSprintArgs], SprintPublic>,
  'updateTask' : ActorMethod<[TaskId, UpdateTaskArgs], TaskPublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];