/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorkspaceId = IDL.Nat;
export const CreateBucketArgs = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'workspaceId' : WorkspaceId,
});
export const BucketId = IDL.Nat;
export const Timestamp = IDL.Int;
export const TaskBucketPublic = IDL.Record({
  'id' : BucketId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'color' : IDL.Text,
  'workspaceId' : WorkspaceId,
});
export const SprintTemplate = IDL.Variant({
  'TwoSprints' : IDL.Null,
  'FourSprints' : IDL.Null,
});
export const CreateMilestoneArgs = IDL.Record({
  'endDate' : Timestamp,
  'name' : IDL.Text,
  'template' : SprintTemplate,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
});
export const MilestoneId = IDL.Nat;
export const UserId = IDL.Principal;
export const MilestonePublic = IDL.Record({
  'id' : MilestoneId,
  'endDate' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
});
export const UpdateProfileArgs = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'avatarUrl' : IDL.Text,
  'department' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'onboardingComplete' : IDL.Bool,
  'avatarUrl' : IDL.Text,
  'department' : IDL.Text,
});
export const CreateSprintArgs = IDL.Record({
  'endDate' : Timestamp,
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
});
export const SprintId = IDL.Nat;
export const SprintStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Planned' : IDL.Null,
  'Completed' : IDL.Null,
});
export const SprintPublic = IDL.Record({
  'id' : SprintId,
  'status' : SprintStatus,
  'endDate' : Timestamp,
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'workspaceId' : WorkspaceId,
  'startDate' : Timestamp,
});
export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const Department = IDL.Variant({
  'Engineering' : IDL.Null,
  'Operations' : IDL.Null,
  'Design' : IDL.Null,
  'Management' : IDL.Null,
  'Marketing' : IDL.Null,
});
export const Column = IDL.Variant({
  'Blocked' : IDL.Null,
  'Done' : IDL.Null,
  'Todo' : IDL.Null,
  'Doing' : IDL.Null,
});
export const CreateTaskArgs = IDL.Record({
  'title' : IDL.Text,
  'assigneeId' : IDL.Opt(UserId),
  'order' : IDL.Nat,
  'sprintId' : IDL.Opt(SprintId),
  'dueDate' : IDL.Opt(Timestamp),
  'bucketId' : IDL.Opt(BucketId),
  'description' : IDL.Text,
  'workspaceId' : WorkspaceId,
  'priority' : Priority,
  'department' : IDL.Opt(Department),
  'columnId' : Column,
});
export const TaskId = IDL.Nat;
export const TaskStatus = IDL.Variant({
  'Blocked' : IDL.Null,
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const TaskPublic = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'blockerReason' : IDL.Text,
  'assigneeId' : IDL.Opt(UserId),
  'order' : IDL.Nat,
  'sprintId' : IDL.Opt(SprintId),
  'createdAt' : Timestamp,
  'dueDate' : IDL.Opt(Timestamp),
  'bucketId' : IDL.Opt(BucketId),
  'description' : IDL.Text,
  'workspaceId' : WorkspaceId,
  'priority' : Priority,
  'department' : IDL.Opt(Department),
  'columnId' : Column,
});
export const CreateWorkspaceArgs = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const Workspace = IDL.Record({
  'id' : WorkspaceId,
  'ownerId' : UserId,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'logoUrl' : IDL.Text,
});
export const MemberRole = IDL.Variant({
  'Lead' : IDL.Null,
  'Member' : IDL.Null,
  'Admin' : IDL.Null,
  'CoCreator' : IDL.Null,
});
export const WorkspaceMember = IDL.Record({
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : MemberRole,
});
export const MoveTaskArgs = IDL.Record({
  'blockerReason' : IDL.Text,
  'newOrder' : IDL.Nat,
  'newColumn' : Column,
  'taskId' : TaskId,
});
export const UpdateBucketArgs = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const UpdateMilestoneArgs = IDL.Record({
  'endDate' : Timestamp,
  'name' : IDL.Text,
  'startDate' : Timestamp,
});
export const UpdateSprintArgs = IDL.Record({
  'status' : SprintStatus,
  'endDate' : Timestamp,
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'startDate' : Timestamp,
});
export const UpdateTaskArgs = IDL.Record({
  'status' : TaskStatus,
  'title' : IDL.Text,
  'blockerReason' : IDL.Text,
  'assigneeId' : IDL.Opt(UserId),
  'order' : IDL.Nat,
  'sprintId' : IDL.Opt(SprintId),
  'dueDate' : IDL.Opt(Timestamp),
  'bucketId' : IDL.Opt(BucketId),
  'description' : IDL.Text,
  'priority' : Priority,
  'department' : IDL.Opt(Department),
  'columnId' : Column,
});

export const idlService = IDL.Service({
  'completeOnboarding' : IDL.Func([], [], []),
  'createBucket' : IDL.Func([CreateBucketArgs], [TaskBucketPublic], []),
  'createMilestone' : IDL.Func([CreateMilestoneArgs], [MilestonePublic], []),
  'createOrUpdateProfile' : IDL.Func(
      [UpdateProfileArgs],
      [UserProfilePublic],
      [],
    ),
  'createSprint' : IDL.Func([CreateSprintArgs], [SprintPublic], []),
  'createTask' : IDL.Func([CreateTaskArgs], [TaskPublic], []),
  'createWorkspace' : IDL.Func([CreateWorkspaceArgs], [Workspace], []),
  'deleteBucket' : IDL.Func([BucketId], [], []),
  'deleteMilestone' : IDL.Func([MilestoneId], [], []),
  'deleteSprint' : IDL.Func([SprintId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getActiveSprint' : IDL.Func(
      [WorkspaceId],
      [IDL.Opt(SprintPublic)],
      ['query'],
    ),
  'getBucket' : IDL.Func([BucketId], [IDL.Opt(TaskBucketPublic)], ['query']),
  'getMilestone' : IDL.Func(
      [MilestoneId],
      [IDL.Opt(MilestonePublic)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'getMyWorkspaces' : IDL.Func([], [IDL.Vec(Workspace)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
  'getSprint' : IDL.Func([SprintId], [IDL.Opt(SprintPublic)], ['query']),
  'getSprintInviteLink' : IDL.Func([SprintId], [IDL.Text], []),
  'getSprintInviteLinkQuery' : IDL.Func(
      [SprintId],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskPublic)], ['query']),
  'getWorkspace' : IDL.Func([WorkspaceId], [IDL.Opt(Workspace)], ['query']),
  'getWorkspaceOwner' : IDL.Func([WorkspaceId], [IDL.Opt(UserId)], ['query']),
  'initSampleData' : IDL.Func([], [], []),
  'inviteMember' : IDL.Func([WorkspaceId, UserId, MemberRole], [], []),
  'isWorkspaceCreator' : IDL.Func([WorkspaceId], [IDL.Bool], ['query']),
  'listBuckets' : IDL.Func(
      [WorkspaceId],
      [IDL.Vec(TaskBucketPublic)],
      ['query'],
    ),
  'listMembers' : IDL.Func(
      [WorkspaceId],
      [IDL.Vec(WorkspaceMember)],
      ['query'],
    ),
  'listMilestones' : IDL.Func(
      [WorkspaceId],
      [IDL.Vec(MilestonePublic)],
      ['query'],
    ),
  'listSprints' : IDL.Func([WorkspaceId], [IDL.Vec(SprintPublic)], ['query']),
  'listTasksByAssignee' : IDL.Func(
      [WorkspaceId, UserId],
      [IDL.Vec(TaskPublic)],
      ['query'],
    ),
  'listTasksByColumn' : IDL.Func(
      [WorkspaceId, Column],
      [IDL.Vec(TaskPublic)],
      ['query'],
    ),
  'listTasksBySprint' : IDL.Func(
      [WorkspaceId, SprintId],
      [IDL.Vec(TaskPublic)],
      ['query'],
    ),
  'moveTask' : IDL.Func([MoveTaskArgs], [TaskPublic], []),
  'registerProfile' : IDL.Func([], [UserProfilePublic], []),
  'removeMember' : IDL.Func([WorkspaceId, UserId], [], []),
  'setSprintStatus' : IDL.Func([SprintId, SprintStatus], [SprintPublic], []),
  'updateBucket' : IDL.Func(
      [BucketId, UpdateBucketArgs],
      [TaskBucketPublic],
      [],
    ),
  'updateMemberRole' : IDL.Func([WorkspaceId, UserId, MemberRole], [], []),
  'updateMilestone' : IDL.Func(
      [MilestoneId, UpdateMilestoneArgs],
      [MilestonePublic],
      [],
    ),
  'updateSprint' : IDL.Func([SprintId, UpdateSprintArgs], [SprintPublic], []),
  'updateTask' : IDL.Func([TaskId, UpdateTaskArgs], [TaskPublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorkspaceId = IDL.Nat;
  const CreateBucketArgs = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'workspaceId' : WorkspaceId,
  });
  const BucketId = IDL.Nat;
  const Timestamp = IDL.Int;
  const TaskBucketPublic = IDL.Record({
    'id' : BucketId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'color' : IDL.Text,
    'workspaceId' : WorkspaceId,
  });
  const SprintTemplate = IDL.Variant({
    'TwoSprints' : IDL.Null,
    'FourSprints' : IDL.Null,
  });
  const CreateMilestoneArgs = IDL.Record({
    'endDate' : Timestamp,
    'name' : IDL.Text,
    'template' : SprintTemplate,
    'workspaceId' : WorkspaceId,
    'startDate' : Timestamp,
  });
  const MilestoneId = IDL.Nat;
  const UserId = IDL.Principal;
  const MilestonePublic = IDL.Record({
    'id' : MilestoneId,
    'endDate' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'workspaceId' : WorkspaceId,
    'startDate' : Timestamp,
  });
  const UpdateProfileArgs = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'avatarUrl' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'onboardingComplete' : IDL.Bool,
    'avatarUrl' : IDL.Text,
    'department' : IDL.Text,
  });
  const CreateSprintArgs = IDL.Record({
    'endDate' : Timestamp,
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'workspaceId' : WorkspaceId,
    'startDate' : Timestamp,
  });
  const SprintId = IDL.Nat;
  const SprintStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Planned' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const SprintPublic = IDL.Record({
    'id' : SprintId,
    'status' : SprintStatus,
    'endDate' : Timestamp,
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'workspaceId' : WorkspaceId,
    'startDate' : Timestamp,
  });
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const Department = IDL.Variant({
    'Engineering' : IDL.Null,
    'Operations' : IDL.Null,
    'Design' : IDL.Null,
    'Management' : IDL.Null,
    'Marketing' : IDL.Null,
  });
  const Column = IDL.Variant({
    'Blocked' : IDL.Null,
    'Done' : IDL.Null,
    'Todo' : IDL.Null,
    'Doing' : IDL.Null,
  });
  const CreateTaskArgs = IDL.Record({
    'title' : IDL.Text,
    'assigneeId' : IDL.Opt(UserId),
    'order' : IDL.Nat,
    'sprintId' : IDL.Opt(SprintId),
    'dueDate' : IDL.Opt(Timestamp),
    'bucketId' : IDL.Opt(BucketId),
    'description' : IDL.Text,
    'workspaceId' : WorkspaceId,
    'priority' : Priority,
    'department' : IDL.Opt(Department),
    'columnId' : Column,
  });
  const TaskId = IDL.Nat;
  const TaskStatus = IDL.Variant({
    'Blocked' : IDL.Null,
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const TaskPublic = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'blockerReason' : IDL.Text,
    'assigneeId' : IDL.Opt(UserId),
    'order' : IDL.Nat,
    'sprintId' : IDL.Opt(SprintId),
    'createdAt' : Timestamp,
    'dueDate' : IDL.Opt(Timestamp),
    'bucketId' : IDL.Opt(BucketId),
    'description' : IDL.Text,
    'workspaceId' : WorkspaceId,
    'priority' : Priority,
    'department' : IDL.Opt(Department),
    'columnId' : Column,
  });
  const CreateWorkspaceArgs = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const Workspace = IDL.Record({
    'id' : WorkspaceId,
    'ownerId' : UserId,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'logoUrl' : IDL.Text,
  });
  const MemberRole = IDL.Variant({
    'Lead' : IDL.Null,
    'Member' : IDL.Null,
    'Admin' : IDL.Null,
    'CoCreator' : IDL.Null,
  });
  const WorkspaceMember = IDL.Record({
    'userId' : UserId,
    'joinedAt' : Timestamp,
    'role' : MemberRole,
  });
  const MoveTaskArgs = IDL.Record({
    'blockerReason' : IDL.Text,
    'newOrder' : IDL.Nat,
    'newColumn' : Column,
    'taskId' : TaskId,
  });
  const UpdateBucketArgs = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const UpdateMilestoneArgs = IDL.Record({
    'endDate' : Timestamp,
    'name' : IDL.Text,
    'startDate' : Timestamp,
  });
  const UpdateSprintArgs = IDL.Record({
    'status' : SprintStatus,
    'endDate' : Timestamp,
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'startDate' : Timestamp,
  });
  const UpdateTaskArgs = IDL.Record({
    'status' : TaskStatus,
    'title' : IDL.Text,
    'blockerReason' : IDL.Text,
    'assigneeId' : IDL.Opt(UserId),
    'order' : IDL.Nat,
    'sprintId' : IDL.Opt(SprintId),
    'dueDate' : IDL.Opt(Timestamp),
    'bucketId' : IDL.Opt(BucketId),
    'description' : IDL.Text,
    'priority' : Priority,
    'department' : IDL.Opt(Department),
    'columnId' : Column,
  });
  
  return IDL.Service({
    'completeOnboarding' : IDL.Func([], [], []),
    'createBucket' : IDL.Func([CreateBucketArgs], [TaskBucketPublic], []),
    'createMilestone' : IDL.Func([CreateMilestoneArgs], [MilestonePublic], []),
    'createOrUpdateProfile' : IDL.Func(
        [UpdateProfileArgs],
        [UserProfilePublic],
        [],
      ),
    'createSprint' : IDL.Func([CreateSprintArgs], [SprintPublic], []),
    'createTask' : IDL.Func([CreateTaskArgs], [TaskPublic], []),
    'createWorkspace' : IDL.Func([CreateWorkspaceArgs], [Workspace], []),
    'deleteBucket' : IDL.Func([BucketId], [], []),
    'deleteMilestone' : IDL.Func([MilestoneId], [], []),
    'deleteSprint' : IDL.Func([SprintId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getActiveSprint' : IDL.Func(
        [WorkspaceId],
        [IDL.Opt(SprintPublic)],
        ['query'],
      ),
    'getBucket' : IDL.Func([BucketId], [IDL.Opt(TaskBucketPublic)], ['query']),
    'getMilestone' : IDL.Func(
        [MilestoneId],
        [IDL.Opt(MilestonePublic)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'getMyWorkspaces' : IDL.Func([], [IDL.Vec(Workspace)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfilePublic)], ['query']),
    'getSprint' : IDL.Func([SprintId], [IDL.Opt(SprintPublic)], ['query']),
    'getSprintInviteLink' : IDL.Func([SprintId], [IDL.Text], []),
    'getSprintInviteLinkQuery' : IDL.Func(
        [SprintId],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskPublic)], ['query']),
    'getWorkspace' : IDL.Func([WorkspaceId], [IDL.Opt(Workspace)], ['query']),
    'getWorkspaceOwner' : IDL.Func([WorkspaceId], [IDL.Opt(UserId)], ['query']),
    'initSampleData' : IDL.Func([], [], []),
    'inviteMember' : IDL.Func([WorkspaceId, UserId, MemberRole], [], []),
    'isWorkspaceCreator' : IDL.Func([WorkspaceId], [IDL.Bool], ['query']),
    'listBuckets' : IDL.Func(
        [WorkspaceId],
        [IDL.Vec(TaskBucketPublic)],
        ['query'],
      ),
    'listMembers' : IDL.Func(
        [WorkspaceId],
        [IDL.Vec(WorkspaceMember)],
        ['query'],
      ),
    'listMilestones' : IDL.Func(
        [WorkspaceId],
        [IDL.Vec(MilestonePublic)],
        ['query'],
      ),
    'listSprints' : IDL.Func([WorkspaceId], [IDL.Vec(SprintPublic)], ['query']),
    'listTasksByAssignee' : IDL.Func(
        [WorkspaceId, UserId],
        [IDL.Vec(TaskPublic)],
        ['query'],
      ),
    'listTasksByColumn' : IDL.Func(
        [WorkspaceId, Column],
        [IDL.Vec(TaskPublic)],
        ['query'],
      ),
    'listTasksBySprint' : IDL.Func(
        [WorkspaceId, SprintId],
        [IDL.Vec(TaskPublic)],
        ['query'],
      ),
    'moveTask' : IDL.Func([MoveTaskArgs], [TaskPublic], []),
    'registerProfile' : IDL.Func([], [UserProfilePublic], []),
    'removeMember' : IDL.Func([WorkspaceId, UserId], [], []),
    'setSprintStatus' : IDL.Func([SprintId, SprintStatus], [SprintPublic], []),
    'updateBucket' : IDL.Func(
        [BucketId, UpdateBucketArgs],
        [TaskBucketPublic],
        [],
      ),
    'updateMemberRole' : IDL.Func([WorkspaceId, UserId, MemberRole], [], []),
    'updateMilestone' : IDL.Func(
        [MilestoneId, UpdateMilestoneArgs],
        [MilestonePublic],
        [],
      ),
    'updateSprint' : IDL.Func([SprintId, UpdateSprintArgs], [SprintPublic], []),
    'updateTask' : IDL.Func([TaskId, UpdateTaskArgs], [TaskPublic], []),
  });
};

export const init = ({ IDL }) => { return []; };