/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateSprintArgs {
    endDate: Timestamp;
    goal: string;
    name: string;
    workspaceId: WorkspaceId;
    startDate: Timestamp;
}
export type Timestamp = bigint;
export interface SprintPublic {
    id: SprintId;
    status: SprintStatus;
    endDate: Timestamp;
    goal: string;
    name: string;
    createdAt: Timestamp;
    workspaceId: WorkspaceId;
    startDate: Timestamp;
}
export type SprintId = bigint;
export interface UpdateSprintArgs {
    status: SprintStatus;
    endDate: Timestamp;
    goal: string;
    name: string;
    startDate: Timestamp;
}
export interface UpdateProfileArgs {
    bio: string;
    title: string;
    name: string;
    onboardingComplete: boolean;
    avatarUrl: string;
    department: string;
}
export interface UpdateTaskArgs {
    status: TaskStatus;
    title: string;
    blockerReason: string;
    assigneeId?: UserId;
    order: bigint;
    sprintId?: SprintId;
    dueDate?: Timestamp;
    bucketId?: BucketId;
    description: string;
    priority: Priority;
    department?: Department;
    columnId: Column;
}
export interface UpdateBucketArgs {
    name: string;
    color: string;
}
export interface CreateBucketArgs {
    name: string;
    color: string;
    workspaceId: WorkspaceId;
}
export interface TaskPublic {
    id: TaskId;
    status: TaskStatus;
    title: string;
    blockerReason: string;
    assigneeId?: UserId;
    order: bigint;
    sprintId?: SprintId;
    createdAt: Timestamp;
    dueDate?: Timestamp;
    bucketId?: BucketId;
    description: string;
    workspaceId: WorkspaceId;
    priority: Priority;
    department?: Department;
    columnId: Column;
}
export interface CreateWorkspaceArgs {
    tagline: string;
    name: string;
    logoUrl: string;
}
export interface CreateMilestoneArgs {
    endDate: Timestamp;
    name: string;
    template: SprintTemplate;
    workspaceId: WorkspaceId;
    startDate: Timestamp;
}
export type WorkspaceId = bigint;
export interface MoveTaskArgs {
    blockerReason: string;
    newOrder: bigint;
    newColumn: Column;
    taskId: TaskId;
}
export type BucketId = bigint;
export interface UpdateMilestoneArgs {
    endDate: Timestamp;
    name: string;
    startDate: Timestamp;
}
export interface WorkspaceMember {
    userId: UserId;
    joinedAt: Timestamp;
    role: MemberRole;
}
export interface Workspace {
    id: WorkspaceId;
    ownerId: UserId;
    tagline: string;
    name: string;
    createdAt: Timestamp;
    logoUrl: string;
}
export interface TaskBucketPublic {
    id: BucketId;
    name: string;
    createdAt: Timestamp;
    color: string;
    workspaceId: WorkspaceId;
}
export interface UserProfilePublic {
    id: UserId;
    bio: string;
    title: string;
    name: string;
    createdAt: Timestamp;
    onboardingComplete: boolean;
    avatarUrl: string;
    department: string;
}
export interface CreateTaskArgs {
    title: string;
    assigneeId?: UserId;
    order: bigint;
    sprintId?: SprintId;
    dueDate?: Timestamp;
    bucketId?: BucketId;
    description: string;
    workspaceId: WorkspaceId;
    priority: Priority;
    department?: Department;
    columnId: Column;
}
export type UserId = Principal;
export type MilestoneId = bigint;
export type TaskId = bigint;
export interface MilestonePublic {
    id: MilestoneId;
    endDate: Timestamp;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    workspaceId: WorkspaceId;
    startDate: Timestamp;
}
export enum Column {
    Blocked = "Blocked",
    Done = "Done",
    Todo = "Todo",
    Doing = "Doing"
}
export enum Department {
    Engineering = "Engineering",
    Operations = "Operations",
    Design = "Design",
    Management = "Management",
    Marketing = "Marketing"
}
export enum MemberRole {
    Lead = "Lead",
    Member = "Member",
    Admin = "Admin",
    CoCreator = "CoCreator"
}
export enum Priority {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export enum SprintStatus {
    Active = "Active",
    Planned = "Planned",
    Completed = "Completed"
}
export enum SprintTemplate {
    TwoSprints = "TwoSprints",
    FourSprints = "FourSprints"
}
export enum TaskStatus {
    Blocked = "Blocked",
    Open = "Open",
    InProgress = "InProgress",
    Completed = "Completed"
}
export interface backendInterface {
    completeOnboarding(): Promise<void>;
    createBucket(args: CreateBucketArgs): Promise<TaskBucketPublic>;
    createMilestone(args: CreateMilestoneArgs): Promise<MilestonePublic>;
    createOrUpdateProfile(args: UpdateProfileArgs): Promise<UserProfilePublic>;
    createSprint(args: CreateSprintArgs): Promise<SprintPublic>;
    createTask(args: CreateTaskArgs): Promise<TaskPublic>;
    createWorkspace(args: CreateWorkspaceArgs): Promise<Workspace>;
    deleteBucket(bucketId: BucketId): Promise<void>;
    deleteMilestone(milestoneId: MilestoneId): Promise<void>;
    deleteSprint(sprintId: SprintId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    getActiveSprint(workspaceId: WorkspaceId): Promise<SprintPublic | null>;
    getBucket(bucketId: BucketId): Promise<TaskBucketPublic | null>;
    getMilestone(milestoneId: MilestoneId): Promise<MilestonePublic | null>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyWorkspaces(): Promise<Array<Workspace>>;
    getProfile(userId: UserId): Promise<UserProfilePublic | null>;
    getSprint(sprintId: SprintId): Promise<SprintPublic | null>;
    getSprintInviteLink(sprintId: SprintId): Promise<string>;
    getSprintInviteLinkQuery(sprintId: SprintId): Promise<string | null>;
    getTask(taskId: TaskId): Promise<TaskPublic | null>;
    getWorkspace(workspaceId: WorkspaceId): Promise<Workspace | null>;
    getWorkspaceOwner(workspaceId: WorkspaceId): Promise<UserId | null>;
    initSampleData(): Promise<void>;
    inviteMember(workspaceId: WorkspaceId, userId: UserId, role: MemberRole): Promise<void>;
    isWorkspaceCreator(workspaceId: WorkspaceId): Promise<boolean>;
    listBuckets(workspaceId: WorkspaceId): Promise<Array<TaskBucketPublic>>;
    listMembers(workspaceId: WorkspaceId): Promise<Array<WorkspaceMember>>;
    listMilestones(workspaceId: WorkspaceId): Promise<Array<MilestonePublic>>;
    listSprints(workspaceId: WorkspaceId): Promise<Array<SprintPublic>>;
    listTasksByAssignee(workspaceId: WorkspaceId, assigneeId: UserId): Promise<Array<TaskPublic>>;
    listTasksByColumn(workspaceId: WorkspaceId, column: Column): Promise<Array<TaskPublic>>;
    listTasksBySprint(workspaceId: WorkspaceId, sprintId: SprintId): Promise<Array<TaskPublic>>;
    moveTask(args: MoveTaskArgs): Promise<TaskPublic>;
    registerProfile(): Promise<UserProfilePublic>;
    removeMember(workspaceId: WorkspaceId, userId: UserId): Promise<void>;
    setSprintStatus(sprintId: SprintId, status: SprintStatus): Promise<SprintPublic>;
    updateBucket(bucketId: BucketId, args: UpdateBucketArgs): Promise<TaskBucketPublic>;
    updateMemberRole(workspaceId: WorkspaceId, userId: UserId, newRole: MemberRole): Promise<void>;
    updateMilestone(milestoneId: MilestoneId, args: UpdateMilestoneArgs): Promise<MilestonePublic>;
    updateSprint(sprintId: SprintId, args: UpdateSprintArgs): Promise<SprintPublic>;
    updateTask(taskId: TaskId, args: UpdateTaskArgs): Promise<TaskPublic>;
}
import type { BucketId as _BucketId, Column as _Column, CreateMilestoneArgs as _CreateMilestoneArgs, CreateTaskArgs as _CreateTaskArgs, Department as _Department, MemberRole as _MemberRole, MilestonePublic as _MilestonePublic, MoveTaskArgs as _MoveTaskArgs, Priority as _Priority, SprintId as _SprintId, SprintPublic as _SprintPublic, SprintStatus as _SprintStatus, SprintTemplate as _SprintTemplate, TaskBucketPublic as _TaskBucketPublic, TaskId as _TaskId, TaskPublic as _TaskPublic, TaskStatus as _TaskStatus, Timestamp as _Timestamp, UpdateSprintArgs as _UpdateSprintArgs, UpdateTaskArgs as _UpdateTaskArgs, UserId as _UserId, UserProfilePublic as _UserProfilePublic, Workspace as _Workspace, WorkspaceId as _WorkspaceId, WorkspaceMember as _WorkspaceMember } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeOnboarding(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding();
            return result;
        }
    }
    async createBucket(arg0: CreateBucketArgs): Promise<TaskBucketPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createBucket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBucket(arg0);
            return result;
        }
    }
    async createMilestone(arg0: CreateMilestoneArgs): Promise<MilestonePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createMilestone(to_candid_CreateMilestoneArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMilestone(to_candid_CreateMilestoneArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UpdateProfileArgs): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0);
            return result;
        }
    }
    async createSprint(arg0: CreateSprintArgs): Promise<SprintPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createSprint(arg0);
                return from_candid_SprintPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSprint(arg0);
            return from_candid_SprintPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: CreateTaskArgs): Promise<TaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_CreateTaskArgs_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TaskPublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_CreateTaskArgs_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TaskPublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWorkspace(arg0: CreateWorkspaceArgs): Promise<Workspace> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkspace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkspace(arg0);
            return result;
        }
    }
    async deleteBucket(arg0: BucketId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBucket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBucket(arg0);
            return result;
        }
    }
    async deleteMilestone(arg0: MilestoneId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilestone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilestone(arg0);
            return result;
        }
    }
    async deleteSprint(arg0: SprintId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSprint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSprint(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getActiveSprint(arg0: WorkspaceId): Promise<SprintPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSprint(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSprint(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBucket(arg0: BucketId): Promise<TaskBucketPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBucket(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBucket(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMilestone(arg0: MilestoneId): Promise<MilestonePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestone(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestone(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkspaces(): Promise<Array<Workspace>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkspaces();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkspaces();
            return result;
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSprint(arg0: SprintId): Promise<SprintPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSprint(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSprint(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSprintInviteLink(arg0: SprintId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSprintInviteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSprintInviteLink(arg0);
            return result;
        }
    }
    async getSprintInviteLinkQuery(arg0: SprintId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSprintInviteLinkQuery(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSprintInviteLinkQuery(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<TaskPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkspace(arg0: WorkspaceId): Promise<Workspace | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkspace(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkspace(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkspaceOwner(arg0: WorkspaceId): Promise<UserId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkspaceOwner(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkspaceOwner(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async inviteMember(arg0: WorkspaceId, arg1: UserId, arg2: MemberRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteMember(arg0, arg1, to_candid_MemberRole_n39(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteMember(arg0, arg1, to_candid_MemberRole_n39(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async isWorkspaceCreator(arg0: WorkspaceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isWorkspaceCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isWorkspaceCreator(arg0);
            return result;
        }
    }
    async listBuckets(arg0: WorkspaceId): Promise<Array<TaskBucketPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBuckets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBuckets(arg0);
            return result;
        }
    }
    async listMembers(arg0: WorkspaceId): Promise<Array<WorkspaceMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembers(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembers(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMilestones(arg0: WorkspaceId): Promise<Array<MilestonePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMilestones(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMilestones(arg0);
            return result;
        }
    }
    async listSprints(arg0: WorkspaceId): Promise<Array<SprintPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSprints(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSprints(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksByAssignee(arg0: WorkspaceId, arg1: UserId): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByAssignee(arg0, arg1);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByAssignee(arg0, arg1);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksByColumn(arg0: WorkspaceId, arg1: Column): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByColumn(arg0, to_candid_Column_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByColumn(arg0, to_candid_Column_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksBySprint(arg0: WorkspaceId, arg1: SprintId): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksBySprint(arg0, arg1);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksBySprint(arg0, arg1);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveTask(arg0: MoveTaskArgs): Promise<TaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.moveTask(to_candid_MoveTaskArgs_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TaskPublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveTask(to_candid_MoveTaskArgs_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TaskPublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile();
            return result;
        }
    }
    async removeMember(arg0: WorkspaceId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0, arg1);
            return result;
        }
    }
    async setSprintStatus(arg0: SprintId, arg1: SprintStatus): Promise<SprintPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.setSprintStatus(arg0, to_candid_SprintStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return from_candid_SprintPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSprintStatus(arg0, to_candid_SprintStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return from_candid_SprintPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBucket(arg0: BucketId, arg1: UpdateBucketArgs): Promise<TaskBucketPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBucket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBucket(arg0, arg1);
            return result;
        }
    }
    async updateMemberRole(arg0: WorkspaceId, arg1: UserId, arg2: MemberRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberRole(arg0, arg1, to_candid_MemberRole_n39(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberRole(arg0, arg1, to_candid_MemberRole_n39(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMilestone(arg0: MilestoneId, arg1: UpdateMilestoneArgs): Promise<MilestonePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMilestone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMilestone(arg0, arg1);
            return result;
        }
    }
    async updateSprint(arg0: SprintId, arg1: UpdateSprintArgs): Promise<SprintPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSprint(arg0, to_candid_UpdateSprintArgs_n52(this._uploadFile, this._downloadFile, arg1));
                return from_candid_SprintPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSprint(arg0, to_candid_UpdateSprintArgs_n52(this._uploadFile, this._downloadFile, arg1));
            return from_candid_SprintPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: TaskId, arg1: UpdateTaskArgs): Promise<TaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_UpdateTaskArgs_n54(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TaskPublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_UpdateTaskArgs_n54(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TaskPublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Column_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Column): Column {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_MemberRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberRole): MemberRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SprintPublic_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SprintPublic): SprintPublic {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SprintStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SprintStatus): SprintStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPublic): TaskPublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_WorkspaceMember_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkspaceMember): WorkspaceMember {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SprintId]): SprintId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BucketId]): BucketId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : from_candid_Department_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SprintPublic]): SprintPublic | null {
    return value.length === 0 ? null : from_candid_SprintPublic_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskBucketPublic]): TaskBucketPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MilestonePublic]): MilestonePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskPublic]): TaskPublic | null {
    return value.length === 0 ? null : from_candid_TaskPublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Workspace]): Workspace | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    blockerReason: string;
    assigneeId: [] | [_UserId];
    order: bigint;
    sprintId: [] | [_SprintId];
    createdAt: _Timestamp;
    dueDate: [] | [_Timestamp];
    bucketId: [] | [_BucketId];
    description: string;
    workspaceId: _WorkspaceId;
    priority: _Priority;
    department: [] | [_Department];
    columnId: _Column;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    blockerReason: string;
    assigneeId?: UserId;
    order: bigint;
    sprintId?: SprintId;
    createdAt: Timestamp;
    dueDate?: Timestamp;
    bucketId?: BucketId;
    description: string;
    workspaceId: WorkspaceId;
    priority: Priority;
    department?: Department;
    columnId: Column;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        blockerReason: value.blockerReason,
        assigneeId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.assigneeId)),
        order: value.order,
        sprintId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.sprintId)),
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.dueDate)),
        bucketId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.bucketId)),
        description: value.description,
        workspaceId: value.workspaceId,
        priority: from_candid_Priority_n25(_uploadFile, _downloadFile, value.priority),
        department: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.department)),
        columnId: from_candid_Column_n30(_uploadFile, _downloadFile, value.columnId)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    joinedAt: _Timestamp;
    role: _MemberRole;
}): {
    userId: UserId;
    joinedAt: Timestamp;
    role: MemberRole;
} {
    return {
        userId: value.userId,
        joinedAt: value.joinedAt,
        role: from_candid_MemberRole_n44(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SprintId;
    status: _SprintStatus;
    endDate: _Timestamp;
    goal: string;
    name: string;
    createdAt: _Timestamp;
    workspaceId: _WorkspaceId;
    startDate: _Timestamp;
}): {
    id: SprintId;
    status: SprintStatus;
    endDate: Timestamp;
    goal: string;
    name: string;
    createdAt: Timestamp;
    workspaceId: WorkspaceId;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_SprintStatus_n7(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        goal: value.goal,
        name: value.name,
        createdAt: value.createdAt,
        workspaceId: value.workspaceId,
        startDate: value.startDate
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Blocked: null;
} | {
    Open: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): TaskStatus {
    return "Blocked" in value ? TaskStatus.Blocked : "Open" in value ? TaskStatus.Open : "InProgress" in value ? TaskStatus.InProgress : "Completed" in value ? TaskStatus.Completed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): Priority {
    return "Low" in value ? Priority.Low : "High" in value ? Priority.High : "Medium" in value ? Priority.Medium : "Critical" in value ? Priority.Critical : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Engineering: null;
} | {
    Operations: null;
} | {
    Design: null;
} | {
    Management: null;
} | {
    Marketing: null;
}): Department {
    return "Engineering" in value ? Department.Engineering : "Operations" in value ? Department.Operations : "Design" in value ? Department.Design : "Management" in value ? Department.Management : "Marketing" in value ? Department.Marketing : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Blocked: null;
} | {
    Done: null;
} | {
    Todo: null;
} | {
    Doing: null;
}): Column {
    return "Blocked" in value ? Column.Blocked : "Done" in value ? Column.Done : "Todo" in value ? Column.Todo : "Doing" in value ? Column.Doing : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Lead: null;
} | {
    Member: null;
} | {
    Admin: null;
} | {
    CoCreator: null;
}): MemberRole {
    return "Lead" in value ? MemberRole.Lead : "Member" in value ? MemberRole.Member : "Admin" in value ? MemberRole.Admin : "CoCreator" in value ? MemberRole.CoCreator : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Planned: null;
} | {
    Completed: null;
}): SprintStatus {
    return "Active" in value ? SprintStatus.Active : "Planned" in value ? SprintStatus.Planned : "Completed" in value ? SprintStatus.Completed : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkspaceMember>): Array<WorkspaceMember> {
    return value.map((x)=>from_candid_WorkspaceMember_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SprintPublic>): Array<SprintPublic> {
    return value.map((x)=>from_candid_SprintPublic_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskPublic>): Array<TaskPublic> {
    return value.map((x)=>from_candid_TaskPublic_n17(_uploadFile, _downloadFile, x));
}
function to_candid_Column_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Column): _Column {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_CreateMilestoneArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMilestoneArgs): _CreateMilestoneArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTaskArgs_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskArgs): _CreateTaskArgs {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Department_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_MemberRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberRole): _MemberRole {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_MoveTaskArgs_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoveTaskArgs): _MoveTaskArgs {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SprintStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SprintStatus): _SprintStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_SprintTemplate_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SprintTemplate): _SprintTemplate {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSprintArgs_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSprintArgs): _UpdateSprintArgs {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTaskArgs_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTaskArgs): _UpdateTaskArgs {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    assigneeId?: UserId;
    order: bigint;
    sprintId?: SprintId;
    dueDate?: Timestamp;
    bucketId?: BucketId;
    description: string;
    workspaceId: WorkspaceId;
    priority: Priority;
    department?: Department;
    columnId: Column;
}): {
    title: string;
    assigneeId: [] | [_UserId];
    order: bigint;
    sprintId: [] | [_SprintId];
    dueDate: [] | [_Timestamp];
    bucketId: [] | [_BucketId];
    description: string;
    workspaceId: _WorkspaceId;
    priority: _Priority;
    department: [] | [_Department];
    columnId: _Column;
} {
    return {
        title: value.title,
        assigneeId: value.assigneeId ? candid_some(value.assigneeId) : candid_none(),
        order: value.order,
        sprintId: value.sprintId ? candid_some(value.sprintId) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        bucketId: value.bucketId ? candid_some(value.bucketId) : candid_none(),
        description: value.description,
        workspaceId: value.workspaceId,
        priority: to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority),
        department: value.department ? candid_some(to_candid_Department_n13(_uploadFile, _downloadFile, value.department)) : candid_none(),
        columnId: to_candid_Column_n15(_uploadFile, _downloadFile, value.columnId)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: Timestamp;
    name: string;
    template: SprintTemplate;
    workspaceId: WorkspaceId;
    startDate: Timestamp;
}): {
    endDate: _Timestamp;
    name: string;
    template: _SprintTemplate;
    workspaceId: _WorkspaceId;
    startDate: _Timestamp;
} {
    return {
        endDate: value.endDate,
        name: value.name,
        template: to_candid_SprintTemplate_n3(_uploadFile, _downloadFile, value.template),
        workspaceId: value.workspaceId,
        startDate: value.startDate
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blockerReason: string;
    newOrder: bigint;
    newColumn: Column;
    taskId: TaskId;
}): {
    blockerReason: string;
    newOrder: bigint;
    newColumn: _Column;
    taskId: _TaskId;
} {
    return {
        blockerReason: value.blockerReason,
        newOrder: value.newOrder,
        newColumn: to_candid_Column_n15(_uploadFile, _downloadFile, value.newColumn),
        taskId: value.taskId
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SprintStatus;
    endDate: Timestamp;
    goal: string;
    name: string;
    startDate: Timestamp;
}): {
    status: _SprintStatus;
    endDate: _Timestamp;
    goal: string;
    name: string;
    startDate: _Timestamp;
} {
    return {
        status: to_candid_SprintStatus_n50(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        goal: value.goal,
        name: value.name,
        startDate: value.startDate
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TaskStatus;
    title: string;
    blockerReason: string;
    assigneeId?: UserId;
    order: bigint;
    sprintId?: SprintId;
    dueDate?: Timestamp;
    bucketId?: BucketId;
    description: string;
    priority: Priority;
    department?: Department;
    columnId: Column;
}): {
    status: _TaskStatus;
    title: string;
    blockerReason: string;
    assigneeId: [] | [_UserId];
    order: bigint;
    sprintId: [] | [_SprintId];
    dueDate: [] | [_Timestamp];
    bucketId: [] | [_BucketId];
    description: string;
    priority: _Priority;
    department: [] | [_Department];
    columnId: _Column;
} {
    return {
        status: to_candid_TaskStatus_n56(_uploadFile, _downloadFile, value.status),
        title: value.title,
        blockerReason: value.blockerReason,
        assigneeId: value.assigneeId ? candid_some(value.assigneeId) : candid_none(),
        order: value.order,
        sprintId: value.sprintId ? candid_some(value.sprintId) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        bucketId: value.bucketId ? candid_some(value.bucketId) : candid_none(),
        description: value.description,
        priority: to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority),
        department: value.department ? candid_some(to_candid_Department_n13(_uploadFile, _downloadFile, value.department)) : candid_none(),
        columnId: to_candid_Column_n15(_uploadFile, _downloadFile, value.columnId)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
} {
    return value == Priority.Low ? {
        Low: null
    } : value == Priority.High ? {
        High: null
    } : value == Priority.Medium ? {
        Medium: null
    } : value == Priority.Critical ? {
        Critical: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    Engineering: null;
} | {
    Operations: null;
} | {
    Design: null;
} | {
    Management: null;
} | {
    Marketing: null;
} {
    return value == Department.Engineering ? {
        Engineering: null
    } : value == Department.Operations ? {
        Operations: null
    } : value == Department.Design ? {
        Design: null
    } : value == Department.Management ? {
        Management: null
    } : value == Department.Marketing ? {
        Marketing: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Column): {
    Blocked: null;
} | {
    Done: null;
} | {
    Todo: null;
} | {
    Doing: null;
} {
    return value == Column.Blocked ? {
        Blocked: null
    } : value == Column.Done ? {
        Done: null
    } : value == Column.Todo ? {
        Todo: null
    } : value == Column.Doing ? {
        Doing: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SprintTemplate): {
    TwoSprints: null;
} | {
    FourSprints: null;
} {
    return value == SprintTemplate.TwoSprints ? {
        TwoSprints: null
    } : value == SprintTemplate.FourSprints ? {
        FourSprints: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberRole): {
    Lead: null;
} | {
    Member: null;
} | {
    Admin: null;
} | {
    CoCreator: null;
} {
    return value == MemberRole.Lead ? {
        Lead: null
    } : value == MemberRole.Member ? {
        Member: null
    } : value == MemberRole.Admin ? {
        Admin: null
    } : value == MemberRole.CoCreator ? {
        CoCreator: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SprintStatus): {
    Active: null;
} | {
    Planned: null;
} | {
    Completed: null;
} {
    return value == SprintStatus.Active ? {
        Active: null
    } : value == SprintStatus.Planned ? {
        Planned: null
    } : value == SprintStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    Blocked: null;
} | {
    Open: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} {
    return value == TaskStatus.Blocked ? {
        Blocked: null
    } : value == TaskStatus.Open ? {
        Open: null
    } : value == TaskStatus.InProgress ? {
        InProgress: null
    } : value == TaskStatus.Completed ? {
        Completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
